/**
 * Turns wire shapes into the shapes the screens were built against.
 *
 * The components in this app were transcribed from Figma before any API
 * existed, so their props describe a drawing: a flat file list, a fused
 * "Orchid Lab V3" string, a bare hostname, a date that reads "Aug 10". The
 * API describes a system: nested trees, a name and a version label kept
 * apart, a full URL, epoch floats. Neither is wrong. This module is the seam
 * between them, and it exists so that seam lives in exactly one file.
 */
import type { PersonName } from '../components/ui/Avatar'
import type { IconName } from '../components/ui/Icon'
import type { ActivityEntry, ArchiveEntry } from '../data/logs'
import type { ProjectFile } from '../data/project'
import type { PaneEntry, TeamMember } from '../data/team'
import type {
  ActivityEventDto,
  ArchiveRowDto,
  FileNodeDto,
  MemberActivityDto,
  MemberDto,
  OverviewDto,
} from './types'

/**
 * Avatars are PNGs keyed by slug, and PersonName is a closed union of the
 * three that exist. The API returns arbitrary display names, so a member the
 * design never drew has no face to show. Rather than 404 an image, unknown
 * names fall through to `undefined` and callers omit the avatar entirely.
 *
 * The real fix is an avatar URL (or initials) on the member payload; until
 * then, adding a fourth teammate means adding a fourth PNG.
 */
const AVATAR_SLUGS: Record<string, PersonName> = {
  Oliver: 'oliver',
  'Eden Sears': 'eden-sears',
  Juliana: 'juliana',
}

export function avatarFor(name: string): PersonName | undefined {
  return AVATAR_SLUGS[name]
}

export function toProject(dto: OverviewDto) {
  return {
    name: dto.project_name,
    // The design prints one string where the API keeps two fields; a project
    // with nothing pushed to it yet has no version to append.
    version: dto.current_version === null
      ? dto.project_name
      : `${dto.project_name} ${dto.current_version}`,
    // Null until the first deploy. A push alone never sets it -- that is the
    // whole point of Invariant 1 -- so this genuinely can be empty.
    deployHost: dto.deploy_url,
    previewSrc: dto.preview_image,
  }
}

/**
 * The file tree arrives nested; `FileTree` draws a single level, because the
 * source draws folders with a disclosure chevron but never draws one open.
 * So this takes the top level only and keeps the chevron honest -- a folder
 * is marked as one even though its children are not rendered yet.
 *
 * Folders first, then files, each alphabetised: the API returns them in path
 * order, which interleaves the two.
 */
export function toFiles(nodes: FileNodeDto[]): ProjectFile[] {
  return nodes
    .map((node) => ({ name: node.name, isFolder: node.type === 'folder' }))
    .sort((a, b) =>
      a.isFolder === b.isFolder ? a.name.localeCompare(b.name) : a.isFolder ? -1 : 1,
    )
}

export function toTeam(members: MemberDto[], currentUser: string): TeamMember[] {
  return members.flatMap((member) => {
    const id = avatarFor(member.name)
    if (id === undefined) return []
    const self = member.name === currentUser
    return [{
      id,
      // The rail spells the signed-in user "Oliver (You)"; the API just
      // returns the name, so the suffix is presentation and belongs here.
      name: self ? `${member.name} (You)` : member.name,
      // The API has no presence concept at all -- no heartbeat, no socket,
      // no last-seen. Everyone reads as offline until one exists.
      online: false,
      ...(self ? { self: true } : {}),
    }]
  })
}

/**
 * Both log endpoints return oldest-first; both tables read newest-first.
 * (The archive endpoint is already reversed server-side, which is why only
 * the activity feed gets flipped here.)
 */
export function toActivityRows(events: ActivityEventDto[]): ActivityEntry[] {
  return events
    .map((event) => ({
      who: event.actor,
      activity: event.description,
      action: event.action,
      commitId: event.commit_id ?? '',
    }))
    .reverse()
}

/** "Jul 24, 2026 at 08:26 PM" -- the long-form stamp the detail pane draws. */
function longStamp(epochSeconds: number): string {
  const at = new Date(epochSeconds * 1000)
  const day = at.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  const time = at.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
  return `${day} at ${time}`
}

/** "Aug 7" -- the terse stamp the archive table draws, from epoch seconds. */
function shortDate(epochSeconds: number): string {
  return new Date(epochSeconds * 1000).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })
}

export function toArchiveRows(rows: ArchiveRowDto[], projectName: string): ArchiveEntry[] {
  return rows.map((row) => ({
    // Version labels are generated by the backend (V1, V2, ...), so this
    // reads "Orchid Lab V6" where the Figma mock reads "Orchid Lab v2".
    // Same shape, different numbering -- the mock's labels were drawn by
    // hand and no endpoint can reproduce them.
    version: `${projectName} ${row.version_label}`,
    time: shortDate(row.time),
    action: row.action,
    versionLabel: row.version_label,
  }))
}

/** The glyph a row wears is chosen by what kind of file its title names. */
const ICONS: { match: RegExp; icon: IconName; size: number }[] = [
  { match: /\.swift\b/i, icon: 'swift', size: 22 },
  { match: /\.md\b/i, icon: 'book-md', size: 18 },
  { match: /\.css\b/i, icon: 'file', size: 16 },
  { match: /\.[a-z0-9]+\b/i, icon: 'file', size: 16 },
]

function iconFor(title: string) {
  return ICONS.find((entry) => entry.match.test(title)) ?? { icon: 'file' as IconName, size: 16 }
}

/**
 * A teammate's pane. The API returns log lines; the row wants a title, a
 * glyph and a face stack, so most of this is unpicking prose the backend
 * composed: it renders a commit as "Committed {comment}" and a push as
 * "Pushed {comment} to {branch}", and the comment is the part worth showing.
 *
 * The faces are the weak spot. `member_activity` returns no participant
 * list, so there is nothing to build a real stack from -- these are simply
 * the project's other members. Fixing it properly means the endpoint
 * returning a commit's `view_by` recipients.
 */
export function toPaneEntries(
  rows: MemberActivityDto[],
  member: string,
  team: MemberDto[],
): PaneEntry[] {
  const others = team
    .filter((other) => other.name !== member)
    .flatMap((other) => {
      const slug = avatarFor(other.name)
      return slug === undefined ? [] : [slug]
    })

  return rows
    .map((row) => {
      if (row.type === 'push') {
        const title = row.description
          .replace(/^Pushed /, '')
          .replace(/ to [^ ]+$/, '')
          .trim()
        // Pushes are the taller row shape, and passing a subtitle is the
        // only thing that selects it -- see VersionRow.
        return {
          id: row.event_id,
          icon: 'eye' as IconName,
          iconSize: 18,
          title,
          stamp: longStamp(row.timestamp),
          subtitle: 'Preview',
          avatars: others,
        }
      }

      const title = row.description.replace(/^Committed /, '').trim()
      const { icon, size } = iconFor(title)
      return {
        id: row.event_id,
        icon,
        iconSize: size,
        title,
        stamp: longStamp(row.timestamp),
        avatars: others,
        ...(row.commit_id === null ? {} : { commitId: row.commit_id }),
        ...(row.diff === undefined ? {} : { diff: row.diff }),
      }
    })
    .reverse()
}

/**
 * Every file path in a tree, folders flattened away.
 *
 * This is what a Commit or Push actually names: the API addresses files by
 * their full path, so a folder is only ever a grouping in the drawing. Sorted
 * so two builds of the same tree produce the same attachment.
 */
export function flattenFilePaths(nodes: FileNodeDto[]): string[] {
  const out: string[] = []
  const walk = (list: FileNodeDto[]) => {
    for (const node of list) {
      if (node.type === 'file') out.push(node.path)
      else if (node.children !== undefined) walk(node.children)
    }
  }
  walk(nodes)
  return out.sort((a, b) => a.localeCompare(b))
}
